version: '3.4'

services:
  smarthotel.services.roomdevices:
    image: needstobeset.azurecr.io/roomdevices-api:dev
    build:
      context: .
      dockerfile: SmartHotel.Services.RoomDevices/Dockerfile
  smarthotel.services.facilitymanagement:
    image: needstobeset.azurecr.io/facilitymanagement-api:dev
    build:
      context: .
      dockerfile: SmartHotel.Services.FacilityManagement/Dockerfile