apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smarthotel.devices.light.room11
spec:
  template:
    metadata:
      labels:
        app: smarthotel.devices.light.room11
        component: smarthotel.devices.light.room11
    spec:
      containers:
      - name: device-light
        image: smarthoteliot.azurecr.io/device-light:public
        imagePullPolicy: Always
        env:
        - name: HardwareId
          value: 
        - name: IoTHubDeviceConnectionString
          value: 
        - name: ManagementApiUrl
          value: 
        - name: MessageIntervalInMilliSeconds
          value: "5000"
        - name: SasToken
          value: 
        - name: SensorDataType
          value: Light
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smarthotel.devices.thermostat.room11
spec:
  template:
    metadata:
      labels:
        app: smarthotel.devices.thermostat.room11
        component: smarthotel.devices.thermostat.room11
    spec:
      containers:
      - name: device-thermostat
        image: smarthoteliot.azurecr.io/device-thermostat:public
        imagePullPolicy: Always
        env:
        - name: HardwareId
          value: 
        - name: IoTHubDeviceConnectionString
          value: 
        - name: ManagementApiUrl
          value: 
        - name: MessageIntervalInMilliSeconds
          value: "5000"
        - name: SasToken
          value: 
        - name: SensorDataType
          value: Temperature
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smarthotel.devices.motion.room11
spec:
  template:
    metadata:
      labels:
        app: smarthotel.devices.motion.room11
        component: smarthotel.devices.motion.room11
    spec:
      containers:
      - name: device-motion
        image: smarthoteliot.azurecr.io/device-motion:public
        imagePullPolicy: Always
        env:
        - name: HardwareId
          value: 
        - name: ManagementApiUrl
          value: 
        - name: MessageIntervalInMilliSeconds
          value: "5000"
        - name: RandomizationDelay
          value: "60000"
        - name: SasToken
          value: 
        - name: SensorDataType
          value: Motion