version: '3.4'

services:
  sh.d.light.smarthotel360_sh360elite1_room101:
    image: smarthoteliot.azurecr.io/device-light:dev
    build:
      context: .
      dockerfile: SmartHotel.Devices.Light/Dockerfile

  sh.d.thermostat.smarthotel360_sh360elite1_room101:
    image: smarthoteliot.azurecr.io/device-thermostat:dev
    build:
      context: .
      dockerfile: SmartHotel.Devices.Thermostat/Dockerfile

  sh.d.motion.smarthotel360_sh360elite1_room101:
    image: smarthoteliot.azurecr.io/device-motion:dev
    build:
      context: .
      dockerfile: SmartHotel.Devices.Motion/Dockerfile