version: '3.4'

services:
  smarthotel.facilitymanagementweb:
    image: smarthoteliot.azurecr.io/facility-management-web
    build:
      context: .
      dockerfile: SmartHotel.FacilityManagementWeb/Dockerfile
