version: '3.4'

services:
# Floor 1 Sensors
# =====================
# BEGIN Room 11 Sensors
  smarthotel.devices.light.room11:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.thermostat.room11:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.motion.room11:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 11 Sensors

# BEGIN Room 12 Sensors
  smarthotel.devices.light.room12:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room12:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room12:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 12 Sensors

# BEGIN Room 13 Sensors
  smarthotel.devices.light.room13:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room13:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room13:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 13 Sensors
# END Floor 1 Sensors

# Floor 2 Sensors
# =====================
# BEGIN Room 21 Sensors
  smarthotel.devices.light.room21:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.thermostat.room21:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.motion.room21:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 21 Sensors

# BEGIN Room 22 Sensors
  smarthotel.devices.light.room22:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room22:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room22:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 22 Sensors

# BEGIN Room 23 Sensors
  smarthotel.devices.light.room23:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room23:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room23:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 23 Sensors
# END Floor 2 Sensors

# Floor 3 Sensors
# =====================
# BEGIN Room 31 Sensors
  smarthotel.devices.light.room31:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.thermostat.room31:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - IoTHubDeviceConnectionString=

  smarthotel.devices.motion.room31:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 31 Sensors

# BEGIN Room 32 Sensors
  smarthotel.devices.light.room32:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room32:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room32:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 32 Sensors

# BEGIN Room 33 Sensors
  smarthotel.devices.light.room33:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room33:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room33:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 33 Sensors
# END Floor 3 Sensors

# Floor 4 Sensors
# ===============
# BEGIN Room 41 Sensors
  smarthotel.devices.light.room41:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room41:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room41:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 41 Sensors

# BEGIN Room 42 Sensors
  smarthotel.devices.light.room42:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room42:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room42:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 42 Sensors

# BEGIN Room 43 Sensors
  smarthotel.devices.light.room43:
    image: smarthoteliot.azurecr.io/device-light:public
    environment:
      - SensorDataType=Light
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.thermostat.room43:
    image: smarthoteliot.azurecr.io/device-thermostat:public
    environment:
      - SensorDataType=Temperature
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=

  smarthotel.devices.motion.room43:
    image: smarthoteliot.azurecr.io/device-motion:public
    environment:
      - SensorDataType=Motion
      - HardwareId=
      - ManagementApiUrl=
      - MessageIntervalInMilliSeconds=5000
      - SasToken=
      - RandomizationDelay=60000
# END Room 43 Sensors